### PR TITLE
Support WebP and HEIC images

### PR DESCRIPTION
**Pull request by wereHamster**
There are two places which need to be updated to handle these modern image formats:

 - Extracting the color palettes from the image (using [node-vibrant](https://www.npmjs.com/package/node-vibrant) and [jimp](https://www.npmjs.com/package/jimp))
 - When passing the image to the [primitive](https://github.com/fogleman/primitive) CLI tool (which supports PNG/JPG/SVG/GIF only)

This PR adds `sharp` as dependency to the sqip-plugin-primitive plugin, and unconditionally converts the image to PNG before passing as input to the CLI tool. Alternative I considered is converting to a common image format (PNG) before passing the buffer to all plugins (so that plugins could rely on the buffer always being a PNG and not having to convert it themselves).

Regarding HEIC support: seems like sharp doesn't support it out of the box, you need a system-provided libvips (the libvips version shipped in the npm package doesn't contain HEIC support due to patent concerns). The error the user will see is somthing like this:

> node:internal/process/promises:246
>           triggerUncaughtException(err, true /* fromPromise */);
>           ^
> 
> [Error: source: bad seek to 293616
> heif: Unsupported feature: Unsupported codec (4.3000)
> ]

Tests were being done by downloading sample files from https://filesamples.com/formats/{heic,heif,webp} and trying to apply sqip via the following script:

```js
const { sqip } = require('./packages/sqip/dist/sqip')

sqip({
  input: '<path-to>/sample1.{heic,heif,webp}'
})
```

Confirmed for…

 - [x] webp
 - [x] heic
 - [x] heif

### CODE REVIEW

**Comment by axe312ger** [comment]
Thank you for the work!!

Uff what a weird error message in the unit tests, especially since it only happens in this PR o.O



Do I understand you correctly, that we will then support WebP but for HEIC the users need to get their own sharp binary?

**Comment by wereHamster** [comment]
No, they'll need to have a system-provided libvips (that includes support for HEIC) when installing sharp (node_modules). The way I understand it, sharp will pick a system libvips if available, and otherwise get the precompiled one.

I'm using nix, and it works for me when I make libvips available before running `npm install`. Users on macOS can install libvips via homebrew, users on Linux via their package manager. Some linux distros may compile libvips without HEIC support, no idea though.

**Comment by axe312ger** [comment]
@wereHamster great. Unfortunately you broke the unit tests:

`packages/sqip-plugin-primitive/__tests__/unit/sqip-plugin-primitive.test.ts`

`executes primitive with default config` and friends complain:

`Input buffer contains unsupported image format`

If you get these errors fixed, we can merge this PR! :)

**Comment by wereHamster** [comment]
I'll have a look today.

**Comment by wereHamster** [comment]
All tests are green now.

btw tests fail locally (for sqip-plugin-cli), because the line wrapping of the help output is different on my local machine (actually GitHub codespaces) vs what's in the snapshot:

image

**Comment by axe312ger** [comment]
@wereHamster thanks! If you rebase on master, I adjusted the tests that annoy around locally. Exactly the ones you mention.


I was about to merge, but 7000 extra lines in the snapshot? How come it is so insane big now? 😱

**Comment by wereHamster** [comment]
I recommend that you squash the changes as I haven't paid attention to clean commits.

The diff is because the test now passes an actual image to the primitive tool, instead of dummy data (a string, previously). The snapshot captures the input, now thinking about it the input might change when when a newer sharp version decides to use a different algorithm to create the buffer. Maybe the test should ignore the input to the primitive cli and just capture the commandline arguments?

**Comment by axe312ger** [comment]
Yes, thanks! I think its fine how you changed the tests. Code does LGTM as well.

Great how unit tests pass but exit with error code 1 :D

**Comment by axe312ger** [comment]
Found a fix for the unit test issue and pushed to master.

Thank you so much for your work, we now support modern image formats :)

**Comment by axe312ger** [comment]
Released as new canary: `sqip@1.0.0-alpha.36`

Have fun with it!

**Pull request merged**
