### PR TITLE
Avoid temporary file for primitive input

### PR DESCRIPTION
**Pull request by maxnordlund**
This uses primitives new `-o -` option to print the resulting SVG to stdout. That means we don't need to use a temporary file to capture the output, which both means one less dependency and running a tad bit faster. Though to be fair, the run time for primitive dwarfs pretty much all IO.

https://github.com/fogleman/primitive/pull/71

In the future I would like to be able to pipe to `sqip` itself, and/or give a `Buffer` as input rather then a file. This is the first step, but even if that's not implemented this is an improvement none then less.

---

I tried to use `execa.stout` but the test broke and I since I haven't used jest I couldn't get it to mock like I wanted.

### CODE REVIEW

**Comment by axe312ger** [comment]
Hey @maxnordlund,

thank you so much! I'll have a look, thats one of the things we wanted to do anyways soon :)

**Comment by axe312ger** [comment]
CI should now build for forked requests as well since we have no confidential secrets in the build :)

**Comment by maxnordlund** [comment]
No problem, always happy to help :)

**Comment by maxnordlund** [comment]
I have no idea why the test failed, maybe you know @axe312ger?

**Comment by axe312ger** [comment]
Meh, we had this two days ago already. This particular tests seem to fail sometimes on the CI. Never had it locally. I restarted the CI, should be fine now.

**Comment by maxnordlund** [comment]
Darn it, the test coverage went down. I would really appreciate help with adding more tests.

**Comment by axe312ger** [comment]
Feel free to extend the unit tests to check if it is passing the data correctly into primitive. This should be enough the get the same/higher coverage :)

**Comment by maxnordlund** [comment]
OK, I'll try to do that, but since I haven't used jest before it might take quite some time.

**Comment by maxnordlund** [comment]
Done, and also added one more test for index.js to get 100% coverage.

**Comment by axe312ger** [comment]
Thank you :)

**Comment by maxnordlund** [comment]
No problem :)

**Pull request merged**
